version: '3.1'

services:
  client:
    build: ./client/container
    ports:
      - "8080:8080"
    volumes:
      - ./client/desafio-irancho:/app/src
    depends_on:
      - server

  server:
    build: ./server/container
    ports:
      - "8081:8080"
    volumes:
      - ./server/src:/app/src
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=senha_do_root
      - MYSQL_DATABASE=desafio_irancho
      - MYSQL_USER=desafio_irancho_user
      - MYSQL_PASSWORD=desafio_irancho_senha

    # se quiser que os dados persistam, descomente o volume abaixo
    # volumes:
    #   - ./mysql:/var/lib/mysql

  # para rodar o adminer na porta 8082, basta descomentar o serviço abaixo
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8082:8080"
  #   links:
  #     - mysql:db